### ISSUE TITLE
GodotRun command 'Not an editor command'

### ISSUE THREAD

**Issue by CaptainKraft** [habamax/vim-godot#14]
I'm on Arch Linux using Vim.

It looks like syntax highlighting is working, but for some reason, Vim doesn't recognize the GodotRun commands at all.

**Comment by habamax** [comment]
1. check what is your filetype with `set ft?`
2. check if you have `~/.vim/pack/...../start/vim-godot/ftplugin/gdscript.vim`
3. check the output of `:scriptnames`, there should be `ftplugin/gdscript.vim` there

Basically, make sure you have installed it correctly.

**Comment by habamax** [comment]
Also try to execute following command when you have opened `.gd` file:

```
command! -buffer -nargs=? -complete=customlist,godot#scene_complete GodotRun call godot#run(<q-args>)
```
and after it try `GodotRun`
