### ISSUE TITLE
Unable to find Godot executable

### ISSUE THREAD

**Issue by sooonism** [habamax/vim-godot#16]
This maybe fundamental, but when I run:

`:GodotRun`

I got this error:

> Unable to find Godot executable, please specify g:godot_executable.

How to resolve this?

**Comment by habamax** [comment]
godot executable is not in the path.

https://github.com/habamax/vim-godot/blob/8fd5bbdc3dcc9eacfccfce83456912d62235e6fc/autoload/godot.vim#L48

Set `g:godot_executable` to the full path of godot executable.
