### ISSUE TITLE
Filetype plugins seem unnecessarily opinionated with regards to expandtab

### ISSUE THREAD

**Issue by codeclem** [habamax/vim-godot#17]
I prefer to use spaces over tabs so I `set expandtab` in my vim config. I have also changed the Godot editor settings to use spaces instead of tabs. However the filetype plugins of `vim-godot` override this with `set noexpandtab`. I understand the reasoning is probably just trying to make this plugin work with the default settings of the Godot editor, but vim by default does not set expandtab anyway. So if you use the default Godot settings and the default vim settings, there is no conflict. If I change the Godot setting, then in my opinion it's my job to also change vim's to match, not for the plugin to assume I use the default. So as it is, I either have to override `vim-godot` in the after directory, so I have to set `expandtab` twice in two different places, or I have to reach into the plugin itself and modify it. Neither of which are ideal when there's no reason for the plugin to do it in the first place. Or is there a reason I'm not seeing?

Thoughts?

**Comment by habamax** [comment]
I don't have strong preferences myself as I don't see a problem setting my own preference in my `after` directory.

So in the beginning `expandtab` wasn't there and I just had `after/godot.vim` file with my settings, including `set noexpandtab`.

Then a new contributor find out that gdscript guidelines suggest to use tabs over spaces and thus by default gdscript uses tabs, the same way python uses spaces, makefiles tabs etc (no matter if you have set expandtab in your vimrc)
