### ISSUE TITLE
Highlight functions

### ISSUE THREAD

**Issue by Shatur95** [habamax/vim-godot#2]
Hello! Thank you for your plugin. I suggest to add function highlighting. Here another [plugin](https://github.com/clktmr/vim-gdscript3) (this is maintained fork) that have good highlighting but do not allow to run Godot from Vim.

**Comment by habamax** [comment]
Do you want this to be highlighted as Function:
![image](https://user-images.githubusercontent.com/234774/81545000-ee388580-9380-11ea-9723-a835afb513e0.png)

It was at some point but... looked so "too much syntax" that I have removed it (to be frank I even created a matched colorscheme and highlighting was almost exact godot has, then I killed it as it only was suitable for godot code).

I can provide Syntax group for "function(calls)" not linked to any default highlighting so anyone can link it to whatever is preferred.

**Comment by Shatur95** [comment]
> Do you want this to be highlighted as Function:

Yes :)

> I can provide Syntax group for "function(calls)" not linked to any default highlighting so anyone can link it to whatever is preferred.

As for me it would be better to have it linked by default. It would be nice to have similar highlighting as in Godot.

**Comment by habamax** [comment]
Similar highlighting is for colorscheme designers. 

glsl syntax would be nice indeed. But it needs another issue to track and not forget to implement it.

**Comment by Shatur95** [comment]
> Similar highlighting is for colorscheme designers.

Of course, I meant to highlight everything in same way (such as use `Function` group for functions, etc.).

Thanks for the implementation!

> glsl syntax would be nice indeed. But it needs another issue to track and not forget to implement it.

Okay, I will open it :)
