### ISSUE TITLE
Is linting files possible?

### ISSUE THREAD

**Issue by niceloaf** [habamax/vim-godot#21]
I am just wondering if linting is possible to add? Or maybe this is a problem that I have to tackle myself?

**Comment by habamax** [comment]
Not to this plugin. Linting is the problem other plugins solve -- ALE, for example. But it also depends on the linting tools which I am not aware of, except godot itself.

YCM gives me some linting (coc.nvim does it also):
![image](https://user-images.githubusercontent.com/234774/96408052-5c645c80-11eb-11eb-9320-8cc291994418.png)
