### ISSUE TITLE
Plugin changes .vimrc expandtab and other options

### ISSUE THREAD

**Issue by sQu1rr** [habamax/vim-godot#26]
https://github.com/habamax/vim-godot/blob/7697cc88a9ae3e5da923a1739f9753ec4c47617b/ftplugin/gdscript.vim#L24

I submit that the plugin should not dictate personal styling preferences. Godot allows to use spaces instead of tabs, and not expanding tabs is an issue for me. I have to fix it in my after/ftplugin scripts myself.

**Comment by habamax** [comment]
> the plugin should not dictate personal styling preferences

What about python? 
https://github.com/vim/vim/blob/23515b4ef7580af8b9d3b964a558ab2007cacda5/runtime/ftplugin/python.vim#L119

Rust?
https://github.com/vim/vim/blob/23515b4ef7580af8b9d3b964a558ab2007cacda5/runtime/ftplugin/rust.vim#L43

And some others too.

Don't get me wrong, there was `noexpandtab` in the beginning. And I had and still have it in a personal `after/ftplugin/gdscript.vim` file. 

Then one of the contributors added it to match defaults that godot editor has. 

I don't see a problem here as you can setup/override it the way you like in your settings.

**Comment by sQu1rr** [comment]
after some research I know realised that the tabs are indeed recommended, for some reason I assumed they are not
