### ISSUE TITLE
Help dealing with 'res://' when jumping to symbol

### ISSUE THREAD

**Issue by austinclem1** [habamax/vim-godot#27]
I'm using Coc right now and when I use it to search symbols and jump to one, it jumps to "res://whatever.gd" which doesn't exist, so it opens an empty buffer pointing to that. Any ideas about how to replace res:// with my actual working directory? Thanks

**Comment by habamax** [comment]
Not sure about CoC, I use YCM now and it jumps to definitions just fine.

**Comment by habamax** [comment]
CoC works for me too:

![image](https://user-images.githubusercontent.com/234774/100578524-897c5280-32f3-11eb-8e2a-63a9b1379906.png)

**Comment by habamax** [comment]
This is goto definitions, let me try search symbols

**Comment by austinclem1** [comment]
huh, `:CocList outline` which searches symbols in the current buffer seems to work, and goto definition works. But `:CocList symbols`, which searches symbols for the entire workspace isn't jumping properly. For example if I try and jump to `_ready()` in the file `Actor.gd`, it opens a new buffer at `'res://Actor.gd'` which doesn't exist on my file system, so it just tries to create a new file with that name

**Comment by habamax** [comment]
Closing as it has nothing to do with vim-godot. 

Feel free to add info here if needed.
