### ISSUE TITLE
Add shader syntax

### ISSUE THREAD

**Issue by Shatur95** [habamax/vim-godot#3]
It would be nice to have support for shaders. Something similar is already implemented [here](https://github.com/clktmr/vim-gdscript3/blob/master/syntax/gsl.vim) in `vim-gdscript3` plugin.

**Comment by habamax** [comment]
@Shatur95 if you have time, I would appreciate your help on this too

**Comment by Shatur95** [comment]
Okay, I will try on the weekends :)
