### ISSUE TITLE
Suggestion: using 'find' to find scenes

### ISSUE THREAD

**Issue by bulfonjf** [habamax/vim-godot#30]
Hi. I'm using your pluggin in vim.
I have many scenes in differents paths (e.g: root/mainscene.tscn or root/test/tests.tscn  or root/player/player/tscn)
Searching scenes with fzf only returns mainscene.tscn in my case (mybe I'm doing something wrong, but I press f7 and that happens)

To get all my scenes I changed the function `func! godot#fzf_run_scene(...)` in vim-godot/autoload/godot.vim:

I added one condition more, to use _find_ if it is available, since it looks for all the files with _tscn_ extension, and also includes the path in the results.

```
" FZF completion for godot scene selection :GodotRunFZF<CR>
func! godot#fzf_run_scene(...)
    if !exists('*fzf#run') || !executable('fzf')
        echom "fzf is not installed!"
        return
    endif

    let project_path = s:project_path()

    if executable('find')
        let scenes = 'find . -name "*.tscn"'
    elseif executable('fdfind')
        let scenes = 'fdfind -e tscn --type f --hidden --follow --no-ignore-vcs --exclude .git'
    elseif executable('fd')
        let scenes = 'fd -e tscn --type f --hidden --follow --no-ignore-vcs --exclude .git'
    elseif executable('rg')
        let scenes ='rg -g *.tscn --files --no-ignore-vcs '
    else
        let scenes = split(globpath(project_path, "**/*.tscn"), "\n")
    endif

    return fzf#run(fzf#wrap('scenes', {
                \ 'source':  scenes,
                \ 'sink':    'GodotRun',
                \ 'dir':    project_path,
                \ 'options': '+m --prompt="Scenes> "'
                \}, 0))
```

I know is not robust because the other functions have more configs (like --hidden or --exclude .git) but if this idea looks good for you, you can make that work.
BTW, thanks for the pluggin, is great!

**Comment by habamax** [comment]
Could you pls test it?

Be aware though that find is checked if there is no `fd` or `rd` in your system.
