### ISSUE TITLE
strange editing problem

### ISSUE THREAD

**Issue by loohoo** [habamax/vim-godot#34]
![ooo3](https://user-images.githubusercontent.com/7367421/107112829-97bb9180-6895-11eb-876e-053fed6585ec.gif)

after select item and press 'enter' key, it will insert the selected word, but soon the word will be delete automatically

**Comment by maltalef101** [comment]
The same is happening to me.
Using neovim v0.4.4,
           CoC 0.0.8

**Comment by habamax** [comment]
vim-godot doesn't do anything with completion, so I would suggest to check your config -- what you have mapped to `<CR>` ?

For me it looks like both of you have copied some config from coc readme that "enhances" `<CR>` with some API call which godot language server doesn't support.

**Comment by maltalef101** [comment]
`inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
			\: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
`

I believe it's one of these two remaps, my guess is that it's the first one.

**Comment by Kirottu** [comment]
I have this same issue too.

**Comment by AlbeyAmakiir** [comment]
I'm getting the same issue (Vim 8.0.1568, not Neovim), however I have nothing in my vimrc relating to CoC. As far as I can see, `<CR>` is not mapped to anything other than the default. So, in theory, it shouldn't be CoC that's the problem, right?

**Comment by habamax** [comment]
@AlbeyAmakiir well, idk.

But in any case -- vim-godot has nothing to do with it. The plugin is not responsible for autocompetion.

I don't have this issue with ycm and coc so can't even try to help you

**Comment by AlbeyAmakiir** [comment]
Ah, I found this `coc-settings.json`: https://github.com/rafaeldelboni/dotfiles/blob/299e8a9f32446b272613ff1f133dc0b0db30b2fb/config/nvim/coc-settings.json#L14

So I replaced the default:
`"filetypes": ["gdscript"],`
With:
`"filetypes": ["gd", "gdscript3"],`

This change alone seems to have fixed it for me. I don't know why this works, but if that is more correct, perhaps it would at least be worth updating the readme for this project to reflect that? (Again, I'm on Vim, not Neovim, and I don't know if that makes a difference.)

**Comment by habamax** [comment]
> "filetypes": ["gd", "gdscript3"],

These are filetypes that have nothing to do with vim-godot. So you basically do not turn godot lsp for the `gdscript` filetype this plugin sets up.

![image](https://user-images.githubusercontent.com/234774/114906623-e56af200-9e22-11eb-8320-97816f6d24fe.png)
