### ISSUE TITLE
Cannot run with vim-dispatch

### ISSUE THREAD

**Issue by Laks0** [habamax/vim-godot#35]
I read on the docs that you needed vim-dispatch to have output on the editor, I've installed it but now I can't run my games. 

When I run `:GodotRun`, the game doesn't run and the command line displays `:!godot 'Splash/Splash.tscn' (x11/?)` (Splash/Splash.tscn being my main scene).

If I remove vim-dispatch I can run the game fine, but without the terminal output.

Also, is there a way to run something like floaterm?

**Comment by habamax** [comment]
Try to run `:Spawn godot Splash/Splash.tscn`

**Comment by Laks0** [comment]
Yep, sorry. It was a problem with my tmux configuration.
