### ISSUE TITLE
code completion(coc.nvim) doesn't complete the gdscript 

### ISSUE THREAD

**Issue by sithumgmgcho** [habamax/vim-godot#36]
The plugin work for running scene and other command but coc doesn't complete the code for me. 
For example if I type `v` it should complete the code from top of the suggestion(for example, `var`) but instead, it disappear completely. 
It complete some function but still have issue, for example, if I type `sd` and hit enter, it complete the code from top of the suggestion `set_deferred(` and it doesn't have a `)`
I believe I followed the instructions correctly.

I'm on mac os 10.10, using neovim.

**Comment by habamax** [comment]
this is smth you probably want to check with coc plugin + godot lsp server

**Comment by lygamac** [comment]
I can reproduce this. It only happens with LSP completions, I  guess it's because coc expects a return value from LSP, but it returned an empty value.

As a workaround, you can use filetype plugin to change where `coc#_select_confirm()` to `"\<C-n>"`

**Comment by TobiasDev** [comment]
> I can reproduce this. It only happens with LSP completions, I guess it's because coc expects a return value from LSP, but it returned an empty value.
> 
> As a workaround, you can use filetype plugin to change where `coc#_select_confirm()` to `"\<C-n>"`
> 
> Edit: Completions after `.` works without issue.

Sorry for poking in a closed issues, could you give an example how to fix this? I have the issue that it removes all auto-complete and I'm using a .lua based setup for my nvim (if that matters).

**Comment by lygamac** [comment]
The problem is with Godot 's own LSP so we have to wait them to have it
fixed.

You can remap coc confirm to the next entry in the completion list or just
remove it and use completion from another plugin like Supertab. Use along
with ftplugin so your configuration for other languages are intact.

**Comment by ChenHuaYou** [comment]
try add this to your init.vim , this work for me
inoremap <expr> <CR> complete_info().selected != -1 ?
            \ &filetype == "gdscript3" ? (coc#expandable() ?  "\<C-y>" : "\<C-y><Esc>a") : "\<C-y>"
            \ : "\<C-g>u\<CR>"

**Comment by TobiasDev** [comment]
> try add this to your init.vim , this work for me inoremap complete_info().selected != -1 ? \ &filetype == "gdscript" ? (coc#expandable() ? "<C-y>" : "<C-y>a") : "<C-y>" \ : "<C-g>u<CR>"

Would it be possible to get some help doing the same but with LUA? I sadly don't know lua and I struggle to update this to that.
