### ISSUE TITLE
NeoVim plugin path in README

### ISSUE THREAD

**Issue by whenov** [habamax/vim-godot#42]
Hi @habamax, thanks for this great plugin!

In the README.md, the plugin path of NeoVim should be
```~/.local/share/nvim/site/pack/*/start/vim-godot```
instead of the current one under `.config`

**Comment by habamax** [comment]
It worked for me with `.config` last time I tried. Was there breaking changes and init files from `.config` are not sourced now?

**Comment by whenov** [comment]
@habamax, I am not sure if there was any breaking change. But `.config` is not mentioned at all under `:help packages`. Also check https://github.com/neovim/neovim/issues/5196
