### ISSUE TITLE
Suggestions about highlighting

### ISSUE THREAD

**Issue by Shatur95** [habamax/vim-godot#5]
Thank you for your plugin again. I have some suggestions about highlighting to let it look more consistent with the other languages:

1. Highlight operators (for example, `not` is operator, not keyword)
2. Highlight constants (I mean not `const` keyword). For example, how it looks in [other](https://github.com/clktmr/vim-gdscript3) gdscript plugin:
![изображение](https://user-images.githubusercontent.com/22453358/83813103-661a7700-a6c5-11ea-9957-198455367b3b.png)
2. Highlight words after `signal` and `setget` as a functions
3. Highlight `true` and `false` as `Boolean` (default highlighting group)
4. Highlight user class name as a `Type` (currently it is a `Define`).

**Comment by habamax** [comment]
3) it is already highlighted as function, or did you mean smth else?
![image](https://user-images.githubusercontent.com/234774/83844595-f7aed680-a70f-11ea-8949-0cff9e5aae83.png)

**Comment by habamax** [comment]
Oh, without params it is not highlighted

**Comment by Shatur95** [comment]
> Oh, without params it is not highlighted

Yes, sorry, I didn’t know that the signal is highlighted if it is with parameters. I suggest to highlight both cases.

**Comment by habamax** [comment]
pls check latest master

**Comment by Shatur95** [comment]
Thank you a lot! Looks awesome!

I see that you want to add [built-in classes](https://github.com/habamax/vim-godot/blob/7c01d77bfdff2475719aadb35024996e0d1c838a/syntax/gdscript.vim#L37). You want to list all classes here? I can help you with it.
But I see that `vim-gdscript3` plugin just parses classes. Maybe this approach will be better?

**Comment by Shatur95** [comment]
I found a small bug. In this case `int` will be highlighted as a function:

```gdscript
func func(value: int) -> void:
    pass
```

**Comment by habamax** [comment]
> 
> 
> Thank you a lot! Looks awesome!
> 
> I see that you want to add [built-in classes](https://github.com/habamax/vim-godot/blob/7c01d77bfdff2475719aadb35024996e0d1c838a/syntax/gdscript.vim#L37). You want to list all classes here? I can help you with it.

It would be really nice

> But I see that `vim-gdscript3` plugin just parses classes. Maybe this approach will be better? User defined classes with this will be highlighted too.

Not sure about this. I would like to have builtin classes separately highlighted. 
We can probably have both, highlighted differently.

**Comment by habamax** [comment]
> ```gdscript
> func func(value: int) -> void:
>     pass
> ```

I am not sure how to fix this as `int` is also a function.

![image](https://user-images.githubusercontent.com/234774/83853229-a9a0cf80-a71d-11ea-9420-c5e62c4478f1.png)

**Comment by Shatur95** [comment]
Simply listing all classes will be difficult to maintain in the future... But if you insist - I will send you a PR today after work.

> I am not sure how to fix this as int is also a function.

I think that highlight it as a type in this case is better then highlight it as a function in general.

**Comment by habamax** [comment]
> Simply listing all classes will be difficult to maintain in the future... 

That is true also for built in functions. I don't have strong opinion here, though.

> But if you insist - I will send you a PR today after work.

Let's try it both for classes and functions then. I mean let's get rid of builtin classes and functions.

**Comment by Shatur95** [comment]
> Let's try it both for classes and functions then. I mean let's get rid of builtin classes and functions.

It would be awesome and much simpler to maintain. Do you want to implement it yourself or give me a try?

> I think that highlight it as a type in this case is better then highlight it as a function in general.

Also in QtCreator such things (`int()`, `float()`) highlighted as a type in C / C++. So, I think it's completely okay.

**Comment by habamax** [comment]
I think I managed to do it:

![image](https://user-images.githubusercontent.com/234774/83857092-22eef100-a723-11ea-9c69-bac5e817fff7.png)

**Comment by habamax** [comment]
> 
> 
> > Let's try it both for classes and functions then. I mean let's get rid of builtin classes and functions.
> 
> It would be awesome and much simpler to maintain. Do you want to implement it yourself or give me a try?

Try it :)

**Comment by Shatur95** [comment]
Looks like everything is highlighted properly, cool!
