### ISSUE TITLE
Highlight classes in a generic way

### ISSUE THREAD

**Issue by habamax** [habamax/vim-godot#6]
To ease maintaining builtin class highlighting would be changed to "generic" class highlighting.

You wouldn't be able to distinguish builtin class and user-made one, though.

**Comment by habamax** [comment]
@Shatur95, fyi

**Comment by Shatur95** [comment]
What do you think about things like `Vector3()`? In Godot it highlighted as a type. In almost all IDE's such things is highlighted as a type:

![изображение](https://user-images.githubusercontent.com/22453358/83858160-b83eb500-a724-11ea-9f8b-24c108161528.png)

> You wouldn't be able to distinguish builtin class and user-made one, though.

It's okay, I think :)

**Comment by habamax** [comment]
> 
> 
> What do you think about things like `Vector3()`? In Godot it highlighted as a type. In almost all IDE's such things is highlighted as a type:

It is builtin class currently mapped to Define (which we agreed to get rid of, right?).

And for generic classes link them to Type highlight group.

**Comment by Shatur95** [comment]
Of course, I mean `Vector()` should be highlighted as a Type, not as a function, right? (with braces, I mean).

**Comment by habamax** [comment]
> 
> 
> Of course, I meant `Vector()` should be highlighted as a Type, not as a Function, right? (with braces, I mean).

I guess, so

**Comment by Shatur95** [comment]
Okay, I will try today :)

**Comment by Shatur95** [comment]
Sorry, I forgot to remove TODO from readme :(
Could you update it?

**Comment by habamax** [comment]
Sure, np
