### ISSUE TITLE
Usage with built-in gdscript filetype

### ISSUE THREAD

**Issue by promisedlandt** [habamax/vim-godot#71]
Hello,

I'm using vim-godot with vim 9.1.  
None of the options in vim-godot take effect - `comments` is not set, the `Godot*` commands do not exist, and the `[[` mappings are not set up.

It looks to me like your gdscript ftplugin shipped with vim sets `b:did_ftplugin`, then the ftplugin from vim-godot gets loaded and exits at the first guard because it checks the same variable.  
This is also according to the script order in `scriptnames`.

It seems to me like this should affect everyone, but I couldn't find an issue for this.  
Any ideas?

**Comment by habamax** [comment]
Should work fine:

![image](https://github.com/habamax/vim-godot/assets/234774/327834eb-09f1-452e-a377-2984c7c91524)

![image](https://github.com/habamax/vim-godot/assets/234774/54349ed4-5883-402b-a245-6ff8ac99dafd)

![image](https://github.com/habamax/vim-godot/assets/234774/57902512-9446-4042-a7e4-3c1246e8b9f0)

vim 9.1.205

**Comment by promisedlandt** [comment]
May I ask in which order the two `vim91/ftplugin/gdscript.vim` / `vim-godot/ftplugin/gdscript.vim` appear in your `scriptnames`?  
If the vim-godot one gets sourced first, it would explain why it works for you.

**Comment by promisedlandt** [comment]
> It is standard `runtimepath`, where `.vim/pack/*` comes before everything from installed vim.

Thank you!  
I use Guix to manage my vim plugins, and it's the other way around there. I've fixed it by prepending to `packpath` instead of appending.
